#!/usr/bin/env python
# -*- coding: utf-8 -*-

#execfile('cg-plt.py')
#execfile('acel-u-cg-plt.py')
#execfile('acel-r-cg-plt.py')
#execfile('acel-v-cg-plt.py')
#execfile('velo-r-cg-plt.py')
#execfile('velo-v-cg-plt.py')
#execfile('velo-u-cg-plt.py')
#execfile('eta-cg-plt.py')

execfile('beta-ace-u-cg-plt.py')
execfile('beta-ace-r-cg-plt.py')
execfile('beta-ace-v-cg-plt.py')
execfile('beta-velo-u-cg-plt.py')
execfile('beta-velo-r-cg-plt.py')
execfile('beta-velo-v-cg-plt.py')
execfile('beta-cg-plt.py')
execfile('beta-eta-cg-plt.py')

execfile('r-ace-u-cg-plt.py')
execfile('r-ace-r-cg-plt.py')
execfile('r-ace-v-cg-plt.py')
execfile('r-velo-u-cg-plt.py')
execfile('r-velo-r-cg-plt.py')
execfile('r-velo-v-cg-plt.py')
execfile('r-cg-plt.py')
execfile('r-eta-cg-plt.py')

execfile('leme-ace-u-cg-plt.py')
execfile('leme-ace-r-cg-plt.py')
execfile('leme-ace-v-cg-plt.py')
execfile('leme-velo-u-cg-plt.py')
execfile('leme-velo-r-cg-plt.py')
execfile('leme-velo-v-cg-plt.py')
execfile('leme-cg-plt.py')
execfile('leme-eta-cg-plt.py')

execfile('brl-ace-u-cg-plt.py')
execfile('brl-ace-r-cg-plt.py')
execfile('brl-ace-v-cg-plt.py')
execfile('brl-velo-u-cg-plt.py')
execfile('brl-velo-r-cg-plt.py')
execfile('brl-velo-v-cg-plt.py')
execfile('brl-cg-plt.py')
execfile('brl-eta-cg-plt.py')
