#!/usr/bin/env python
# -*- coding: utf-8 -*-

execfile('xy-zz-plt.py')
execfile('r-zz-plt.py')
execfile('acel-r-zz-plt.py')
execfile('acel-v-zz-plt.py')
execfile('velo-r-zz-plt.py')
execfile('velo-v-zz-plt.py')
execfile('velo-u-zz-plt.py')
execfile('eta-zz-plt.py')

execfile('beta-ace-u-zz-plt.py')
execfile('beta-ace-r-zz-plt.py')
execfile('beta-ace-v-zz-plt.py')
execfile('beta-velo-u-zz-plt.py')
execfile('beta-velo-r-zz-plt.py')
execfile('beta-velo-v-zz-plt.py')
execfile('beta-zz-plt.py')

execfile('r-ace-u-zz-plt.py')
execfile('r-ace-r-zz-plt.py')
execfile('r-ace-v-zz-plt.py')
execfile('r-velo-u-zz-plt.py')
execfile('r-velo-r-zz-plt.py')
execfile('r-velo-v-zz-plt.py')
execfile('r-zz-plt.py')

execfile('leme-ace-u-zz-plt.py')
execfile('leme-ace-r-zz-plt.py')
execfile('leme-ace-v-zz-plt.py')
execfile('leme-velo-u-zz-plt.py')
execfile('leme-velo-r-zz-plt.py')
execfile('leme-velo-v-zz-plt.py')
execfile('leme-zz-plt.py')

execfile('brl-ace-u-zz-plt.py')
execfile('brl-ace-r-zz-plt.py')
execfile('brl-ace-v-zz-plt.py')
execfile('brl-velo-u-zz-plt.py')
execfile('brl-velo-r-zz-plt.py')
execfile('brl-velo-v-zz-plt.py')
execfile('brl-zz-plt.py')